modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Meldexun/UnifiedResources/issues"
[[mods]]
modId="unifiedresources"
version="1.0.2"
displayName="UnifiedResources"
authors="Meldexun"
description=''''''
