modLoader="javafml"
loaderVersion="${mod_loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description=''''''
